#!/bin/bash
#centos
#2023年3月21日更新
cd /tmp
HOSTNAME=$(hostname)
IP=$(hostname -I | cut -d ' ' -f1)
rm "${HOSTNAME}_${IP}.md"
touch "${HOSTNAME}_${IP}.md"
echo "# 基本信息" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "1. 机器名" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`hostname\`" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
hostname >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "2. ip信息" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`hostname -I\`" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
hostname -I >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`ifconfig -a\`" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
ifconfig -a >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "3. BASH漏洞测试" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`env x='() { :;}; echo 有漏洞' bash -c 'echo 无漏洞'\`" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
env x='() { :;}; echo 有漏洞' bash -c 'echo 无漏洞' >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "# 身份鉴别" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "1. **应对登录的用户进行身份标识和鉴别，身份标识具有唯一性，身份鉴别信息具有复杂度要求并定期更换。**" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`grep -v \"^#\" /etc/login.defs | grep PASS\` #密码最长使用90天，最短使用1天，长度大于等于8位。只对新用户有效，旧用户查看下方过期账户测评项。" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
grep -v "^#" /etc/login.defs | grep PASS >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`grep -v \"^#\" /etc/pam.d/passwd\` #先看这个文件include了哪个xxx-auth，再看下方相应文件有无使用相关模块。或者直接配置在这个文件也行。" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
grep -v "^#" /etc/pam.d/passwd  >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`grep -v \"^#\" /etc/pam.d/system-auth |grep pam_cracklib.so\` #查看是否使用密码复杂度模块并规定密码长度大于等于8位，每种符号至少1个(值-1)，与下方模块二选一。" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
grep -v "^#" /etc/pam.d/system-auth |grep pam_cracklib.so >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`grep -v \"^#\" /etc/pam.d/system-auth |grep pam_pwquality.so\` #查看是否使用密码复杂度模块并规定密码长度大于等于8位，每种符号至少1个(值-1)" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
grep -v "^#" /etc/pam.d/system-auth |grep pam_pwquality.so >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`grep -v \"^#\" /etc/pam.d/password-auth |grep pam_cracklib.so\` #查看是否使用密码复杂度模块并规定密码长度大于等于8位，每种符号至少1个(值-1)" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
grep -v "^#" /etc/pam.d/password-auth |grep pam_cracklib.so >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`grep -v \"^#\" /etc/pam.d/password-auth |grep pam_pwquality.so\` #查看是否使用密码复杂度模块并规定密码长度大于等于8位，每种符号至少1个(值-1)" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
grep -v "^#" /etc/pam.d/password-auth |grep pam_pwquality.so >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "2. **应具有登录失败处理功能，应配置并启用结束会话、限制非法登录次数和当登录连接超时自动退出等相关措施。**" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`grep -v \"^#\" /etc/pam.d/login\` #先看这个文件include了哪个xxx-auth，再看下方相应文件有无使用相关模块。或者直接配置在这个文件也行。" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
grep -v "^#" /etc/pam.d/login  >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`grep -v \"^#\" /etc/pam.d/system-auth |grep pam_tally2.so\` #查看是否使用登录失败处理模块,并设置最多失败10次，至少锁定5分钟（值大于等于300），与下方模块二选一。" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
grep -v "^#" /etc/pam.d/system-auth |grep pam_tally2.so >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`grep -v \"^#\" /etc/pam.d/system-auth |grep pam_faillock.so\` #查看是否使用登录失败处理模块,并设置最多失败10次，至少锁定5分钟（值大于等于300）" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
grep -v "^#" /etc/pam.d/system-auth |grep pam_faillock.so >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`grep -v \"^#\" /etc/pam.d/password-auth |grep pam_tally2.so\` #查看是否使用登录失败处理模块,并设置最多失败10次，至少锁定5分钟（值大于等于300）" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
grep -v "^#" /etc/pam.d/password-auth |grep pam_tally2.so >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`grep -v \"^#\" /etc/pam.d/password-auth |grep pam_faillock.so\` #查看是否使用登录失败处理模块,并设置最多失败10次，至少锁定5分钟（值大于等于300）" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
grep -v "^#" /etc/pam.d/password-auth |grep pam_faillock.so >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`cat /etc/profile | grep TMOUT\` #登录超时自动退出，非监控投屏建议不超过10分钟（值少于等于600）,TMOUT值要有export才生效" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
cat /etc/profile | grep TMOUT >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`echo \$TMOUT\` #查看当前值，sudo后未必保留该值，与sudoers配置有关。" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
echo $TMOUT >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "3. **当进行远程管理时，应采取必要措施防止鉴别信息在网络传输过程中被窃听。**" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> 使用ssh或其他远程开加密符合，使用telnet或其他远程不开加密不符合" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md" 
echo "> \`systemctl status sshd\`" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
systemctl  status sshd >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`systemctl  status telnet\`" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
systemctl  status telnet >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "4. **(三级)应采用口令、密码技术、生物技术等两种或两种以上组合的鉴别技术对用户进行身份鉴别，且其中一种鉴别技术至少应使用密码技术来实现。**" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> 除密码以外有OTP、证书、USBkey、指纹、声纹、虹膜符合" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "# 访问控制" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "1. **应对登录的用户分配账户和权限。**" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`grep -vE \"nologin$|false$\" /etc/passwd\` #查看非/sbin/nologin和非/bin/false的用户，询问这些用户的作用。" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
grep -vE "nologin$|false$" /etc/passwd >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`grep -v \"^#\" /etc/ssh/sshd_config | grep PermitRootLogin\` #查看是否允许root远程登录（值为no符合）" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
grep -v "^#" /etc/ssh/sshd_config | grep PermitRootLogin >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "2. **应重命名或删除默认账户，修改默认账户的默认口令。**" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`cat /etc/passwd | grep root\` #是否禁用root，没有root用户或shell字段为nologin或false则符合" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
cat /etc/passwd | grep root >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`passwd -S root\` #是否锁定root密码，与上面其中一个实现则符合。还要看有无改root密码。" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
passwd -S root >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "3. **应及时删除或停用多余的、过期的账户，避免共享账户的存在。**" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`chage -l 用户名\` #查看用户是否过期，过期是否删除或停用；最近90天是否修改密码" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
users=$(getent passwd | grep -vE 'nologin$|false$' | cut -d: -f1)
for user in $users; do
  chage_output=$(chage -l $user)
  echo "$user:" >> "${HOSTNAME}_${IP}.md" 2>&1
  echo "$chage_output" >> "${HOSTNAME}_${IP}.md" 2>&1
  echo "-----" >> "${HOSTNAME}_${IP}.md" 2>&1
done
echo \`\`\` >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "4. **应授予管理用户所需的最小权限，实现管理用户的权限分离。**" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`grep -C 5 'umask' /etc/profile\` #看umask值前后5行，至少拿掉所属组和其他用户的写权限2，即0022。0027（结果所有者全部权限、所属组读写、其他人无）更好。0077（结果所有者全部权限、所属组无、其他人无）最好。" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
grep -C 5 'umask' /etc/profile >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`grep -C 5 'umask' /etc/bashrc\` #看umask值前后5行，其他shell看相应的rc文件，这个会覆盖profile，用户目录的.bashrc会覆盖这个" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
grep -C 5 'umask' /etc/bashrc >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`umask\` #查看当前用户umask值，root默认是022，普通用户默认是002。" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
umask >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`id 用户名\` #查看非/bin/nologin和非/bin/false的用户所属组。询问各组作用，尤其是root组其他用户。" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
for user in $users; do
  id_output=$(id $user)
  echo "$user:" >> "${HOSTNAME}_${IP}.md" 2>&1
  echo "$id_output" >> "${HOSTNAME}_${IP}.md" 2>&1
  echo "-----" >> "${HOSTNAME}_${IP}.md" 2>&1
done
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`grep -v \"^#\" /etc/sudoers\` #查看用户权限划分配置，是否三权分立。" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
grep -v "^#" /etc/sudoers >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`sudo -l\` #查看当前用户权限划分" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
sudo -l >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "5. **（三级）应由授权主体配置访问控制策略，访问控制策略规定主体对客体的访问规则。**" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> 看上方sudoers文件有无配置到文件级别" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "6. **（三级）访问控制的粒度应达到主体为用户级或进程级，客体为文件、数据库表级。**" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> 查看各种文件权限" >> "${HOSTNAME}_${IP}.md"
echo "> \`stat -c '%a %n' /etc/passwd /etc/shadow /etc/group\` #查看权限是否小于等于644" >> "${HOSTNAME}_${IP}.md"
echo "> \`stat -c '%a %n' /etc/*.conf\` #查看权限是否小于等于644" >> "${HOSTNAME}_${IP}.md"
echo "> \`stat -c '%a %n' /etc\`" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
stat -c '%a %n' /etc/passwd /etc/shadow /etc/group >> "${HOSTNAME}_${IP}.md" 2>&1
echo "-----" >> "${HOSTNAME}_${IP}.md" 2>&1
stat -c '%a %n' /etc/*.conf >> "${HOSTNAME}_${IP}.md" 2>&1
echo "-----" >> "${HOSTNAME}_${IP}.md" 2>&1
stat -c '%a %n' /etc >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "7. **（三级）应对重要主体和客体设置安全标记，并控制主体对有安全标记信息资源的访问。**" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> 询问有没有安装使用可信客户端或其他软硬件。" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "# 安全审计" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "1. **应启用安全审计功能，审计覆盖到每个用户，对重要的用户行为和重要安全事件进行审计。**" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`systemctl status rsyslog\` #查看服务是否启动，旧版命令service rsyslog status" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
systemctl status rsyslog >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`grep -v \"^#\" /etc/rsyslog.conf\` #查看rsyslog配置文件的审计内容（auth、authpriv、cron、daemon、kern、lpr、mail、news、syslog、user、uucp、local0-7），有无指定日志服务器" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
grep -v "^#" /etc/rsyslog.conf >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`systemctl status auditd\` #查看服务是否启动，旧版命令service auditd status" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
systemctl status auditd >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`grep -v \"^#\" /etc/audit/audit.rules\` #查看是否配置审计规则" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
grep -v "^#" /etc/audit/audit.rules >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`auditctl -l\` #查看当前审计规则" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
auditctl -l >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "2. **审计记录应包括事件的日期和时间、用户、事件类型、事件是否成功及其他与审计相关的信息。**" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> 查看上方rsyslog配置文件的审计级别（emerg、alert、crit、err、warning、notice、info、debug）" >> "${HOSTNAME}_${IP}.md"
echo "> 查看上方audit审计规则" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "3. **应对审计记录进行保护，定期备份，避免受到未预期的删除、修改或覆盖等。**" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`grep -v \"^#\" /etc/logrotate.conf\` #查看日志清除周期，大于等于 6 个月、24周、180天。" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
grep -v "^#" /etc/logrotate.conf >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`stat -c '%a %n' /etc/rsyslog.conf\` #查看权限是否小于等于644" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
stat -c '%a %n' /etc/rsyslog.conf >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`ls -l /etc/audit/\`  #查看权限是否小于等于644" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
ls -l /etc/audit/ >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`stat -c '%a %n' /var/log/*\` #查看权限" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
stat -c '%a %n' /var/log/* >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> 询问是否手动备份日志。有指向日志服务器符合。" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "4. **（三级）对审计进程进行保护，防止未经授权的中断。**" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> 询问有没有安装使用可信客户端或其他软硬件。" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "# 入侵防范" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "1. **应遵循最小安装的原则，仅安装需要的组件和应用程序。**" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`yum list installed\` #或rpm -qa ，安装的所有软件包" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
yum list installed >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "2. **应关闭不需要的系统服务、默认共享和高危端口。**" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`netstat -lnptu\` #列出所有监听端口，询问相关端口是否需要使用，是否使用防火墙限制准入范围。" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
netstat -lnptu >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`chkconfig --list\` #列出所有服务" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
chkconfig --list >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`systemctl list-unit-files | grep enabled\` #列出所有服务" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
systemctl list-unit-files | grep enabled >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "3. **应通过设定终端接入方式或网络地址范围对通过网络进行管理的管理终端进行限制。**" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> 查看防火墙默认策略是否禁止所有，使用远程运维是否配置允许范围" >> "${HOSTNAME}_${IP}.md"
echo "> \`iptables -nvL\`" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
iptables -nvL >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`firewall-cmd --list-all\`" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
firewall-cmd --list-all >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`grep -v \"^#\" /etc/hosts.allow\`" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
grep -v "^#" /etc/hosts.allow >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`grep -v \"^#\" /etc/hosts.deny\`" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
grep -v "^#" /etc/hosts.deny >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "4. **应能发现可能存在的已知漏洞，并在经过充分测试评估后，及时修补漏洞。**" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> 检查上方软件列表，最近6个月是否更新" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`echo \$HISTSIZE\` #查看历史命令保存条数，建议不多于10条" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
echo $HISTSIZE >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`uname -a\` #查看内核版本，是否使用已停止技术支持的版本" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
uname -a >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`cat /etc/*release\` #查看操作系统版本，是否使用已停止技术支持的版本。" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
cat /etc/*release >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "5. **（三级）应能够检测到对重要节点进行入侵的行为，并在发生严重入侵事件时提供报警。**" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> 询问是否有IDS，IPS等设备。" >> "${HOSTNAME}_${IP}.md"
echo "# 恶意代码" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "1. **应安装防恶意代码软件或配置具有相应功能的软件，并定期进行升级和更新防恶意代码库。**" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`ps -ef | grep kis\` #是否安装并运行安天防病毒软件。有其他防病毒也符合。" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
ps -ef | grep kis >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`cat /opt/LinuxKPC/ini/version\` #查看安天病毒库版本，最近6个月是否更新。" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
cat /opt/LinuxKPC/ini/version >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`ps -ef | grep gov\` #是否安装并运行G01" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
ps -ef | grep gov >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "# 可信验证" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "1. **可基于可信根对计算设备的系统引导程序、系统程序、重要配置参数和应用程序等进行可信验证，并在检测到其可信性受到破坏后进行报警，并将验证结果形成审计记录送至安全管理中心。**" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> TPM国际，TCM国内" >> "${HOSTNAME}_${IP}.md"
echo "> TCM需额外安装物理卡和安装可信软件" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "> \`dmesg | grep -i tpm\` #服务器是否安装tpm模块" >> "${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
dmesg | grep -i tpm >> "${HOSTNAME}_${IP}.md" 2>&1
echo \`\`\` >>"${HOSTNAME}_${IP}.md"
echo "" >> "${HOSTNAME}_${IP}.md"
echo "已完成，请将/tmp目录的以下文件导出"
echo "${HOSTNAME}_${IP}.md"